### PR TITLE
Updated the student council page

### PR DESCRIPTION
**Pull request by sarthak503**

### CODE REVIEW

**Comment by dinskid** [comment]
The changes are sufficient and the code seems to work fine.
To my knowledge, the image files are not added to the repository due to privacy concerns. The image folder can be removed and can be shared with @anoopjt directly. @anoopjt sir, can you please confirm this? We can merge once that is sorted.

**Comment by anoopjt** [comment]
> The changes are sufficient and the code seems to work fine. To my knowledge, the image files are not added to the repository due to privacy concerns. The image folder can be removed and can be shared with @anoopjt directly. @anoopjt sir, can you please confirm this? We can merge once that is sorted.

@dinskid we can do as you mentioned. I will just push the latest changes from the server. You can remove the images, and then merge the PR.

**Comment by anoopjt** [comment]
@dinskid have you checked the change to the port number is working fine, I guess it is just defaulting to 3000 if process.env.Port is not available, where do we set that? @sarthak503

**Comment by dinskid** [comment]
> @dinskid have you checked the change to the port number is working fine, I guess it is just defaulting to 3000 if process.env.Port is not available, where do we set that? @sarthak503

Sir, there is no issue with the port number. Sarthak has updated it to use the environment variable PORT if available, else to default to 3000 (which was the PORT number set already)

**Comment by dinskid** [comment]
I'm merging the PR as all things related to the student council seem to work as expected.

**Pull request merged**
